print("hi my name is jamal")
print(2+3)
print("i am learning python")
print("i am leaning from codanic")
print("Sir is ammar")
print("happy new year")
print(2*1)
print(4/2)
print("Jamal khan")
print("home is beautiful")
print("I won ludo")
print("LMS is learning site")
print("Sudias khan")
print("Rehmetullah khan")
print("JAlal baijan")
print("Subhanullah")
print("Alhamdulillah")